# Machine Learning A-Z Python

## Part 1. Data Preprocessing

In [1]:
### Part 1_Data Preprocessing
# Video_10: Importing the libraries

## Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [6]:
# Video_11: Importing the dataset

''' # Save the code we are going to write in SPYDER in the same folder
where the .csv file is present (to avoid giving file path to .csv file)
and then run the code. 
# Avoid giving path to the .csv file by going to the folder in terminal
and then open Jupter notebook'''

dataset= pd.read_csv('Data.csv')
print(dataset)
print('------------------------------------')
# Now we need to create matrix of independent and dependent variable 
X=dataset.iloc[:,:-1].values # all independent variables
y=dataset.iloc[:,-1].values # dependent variables
# .values as we are trying to create an array
print(X) # confirm it do NOT have dependent variable 
print('------------------------------------')
print(y) # confirm it only contain  dependent variable
print(X.ndim, y.ndim)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
------------------------------------
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
------------------------------------
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
2 1


Dependent variable is 'Purchased' here. Rest are independent variables. ML will use the independent variables to predict the dependent variable.

Dependent variable: Purchased|
Independent variable: Age, Salary, Purchased|
Data preprocessing is common intitial step before starting ML

In [3]:
'''Python object priented programming:
    Class: is the model eg- construction plan
    Object: instance of the class. eg- House prepared from the construction plan
    method: is a tool use on the object to finish a task'''

'Python object priented programming:\n    Class: is the model eg- construction plan\n    Object: instance of the class. eg- House prepared from the construction plan\n    method: is a tool use on the object to finish a task'

In [4]:
# Video_13: Missing Data: We see 2 NaN 

# Strategy 1: Remove observation that contains NaN 
# Strategy 2: Replace Nan by mean of relevant column/row


## Taking care of missing data in the correct way:
from sklearn.preprocessing import Imputer # Imputer class

# as we imported the class, we need to create an object of the class
imputer = Imputer(missing_values= 'NaN', 
                  strategy= 'mean', axis=0) # Imputer object

'''missing_values= 'NaN' because the dataset showed the missing values 
are denoted by NaN

axis=0 mean value will be taken across the column and imputed
axis=1 mean value will be taken across the row and imputed
axis=0 is selcted as we are trying to replace NaN with mean value 
       across a feature/ column
       '''

# Fit imputer to matrix x (only where, missing data is present)
imputer = imputer.fit(X[:,1:]) # 1: because 2nd and 3rd column has NaN values
X[:,1:] = imputer.transform(X[:,1:]) #conversion of matrix x based on imputer
X # see how NaN has been replaced with mean values

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

2 categorical variables in the dataset Country (Independent) and
Purchased (dependent). Country variable contains 3 categories and 
Purchase variable contains 2 categories. We want ONLY numbers for ML and
not text (like in these vategorical features). Thus we need to convert the 
categories into numbers

In [5]:
# Video_14: Categorical variables


# Categorical variable: Country- 3 categories | Purchased-2 categories
# Need to convert categories into numbers for ML 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X=LabelEncoder() # creating labelencoder object
X[:,0]=labelencoder_X.fit_transform(X[:,0])
# X[:,0] because only 1st column of X is categorical
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

We see the country (categorical) column is converted into numerical. 

**But there is a huge PROBLEM.**
3 categories of country column are converted into 0, 1, 2. Since 0 <1 <2, equations in the model will think that 1 country is bigger than other based on the number representing them. ML will think spain is bigger than germany as 2>0. BUT there is **no relational order between the countries**. 

Label encoder encode values without thinking whether there is order or not!

But if we have 3 categories in the same column such as small, medium and large. Then 0,1,2 makes sense as **there is an order between small, medium and large**. But in country there is no order so we have to use something other than LabelEncoder.

### Therefore we have to use  Dummy encoding in the case of country column

In [9]:
'''Dummy encoding will convert 1 country column into 3 columns because 
there are 3 categories. Each dummy variable column 
will represent 1 country. We need OneHotEncoder'''

onehotencoder= OneHotEncoder(categorical_features=[0])
# categorical_features is saying which column we want 
# to convert into dummy variable
X=onehotencoder.fit_transform(X).toarray()
X[0]

array([1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04])

Previously X had 3 columns. Now country column is replaced by 3 dummy variables or columns.
So 3-1+3=5 columns. So OneHotEncoder worked.

In [10]:
# Now for y or target or dependent variable
# LabelEncoder is ok as y is a binary category i.e. 
# purchased or not, True and False
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [11]:
# Video_16: Splitting the dataset into Training and Test set

## Splitting the dataset into the Training and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, 
                                                  test_size=0.2, 
                                                  random_state=0)

We have to be careful about ML algorithem understanding the correlation between X_train and
y_train. If they don't understand the logic between X_train and y_train and just learn it by heart, 
it will have trouble predicting X_test. This is the case where overfitting of data happens. But there are 
regularization techniques to prevent this overfitting

In [12]:
# Video_17: Feature scaling
# Required becoz scale of features are uneven and widely varied

But generally FEATURE SCALING is extremely necessary: Look at the age range and salary range or scale (DATA PREPROCESSING EXAMPLE). Highly different.


ML model depends on euclidian distance. Suppose there are 2 points, then they calculate
euclidian distance by ((y2-y1)^2+(x2-x1)^2)^1/2. Now if one variable (suppose y) here salary
has a way higher scale and then it is squared and added with other square (age here whose 
value is negligible even after squaring) then ML will only consider y value as it is so 
high and thus effect of age won't be considered.
Now feature scaling can be done by

1. STANDARIZARION: x_standarization= x - mean(x) / standard deviation(x)
2. NORMALIZATION: x_normalization= x - min(x) / max(x) - min(x)

So we need to standarize them such that each variable ranges from -1 to +1. 
And thus their high range wont affect ML model to be biased'''


**CODE:**

'''
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)

X_test = sc_X.transform(X_test)'''

If we have to standardscaler y, add the following code to the above code--

'''
sc_y = StandardScaler()

y_train = sc.y.fit_transform(y_train)
'''


For test set, we dont need to fit the sc_X instance because it's already fitted to training set
That means X_test is transformed by StandardScaler based on its fitting to the X_train. So 
both X_train and X_test are fitted based on the same scale.
Don't need to use feature scaling to y_train and y_test in this particular example. 

Here dependent variable or y
is categorical as it has 1 or 0 values, we do NOT need to use feature scaling for clasification.

But for regression where dependent variable or y can take a huge range/scale 
(unlike classification), we need to use feature scaling for y as well.

In [13]:
from sklearn.preprocessing import StandardScaler # StandardScaler class
sc_X = StandardScaler() # creating sc_x, a StandardScaler object
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test) 

For X_test set, we dont need to fit the sc_X instance because it's already fitted to 
training set. That means X_test is transformed by StandardScaler based on its fitting 
to the X_train. So both X_train and X_test are fitted based on the same scale

Don't need to use feature scaling to y_train and y_test. Here dependent variable or y
is categorical as it has 1 or 0 values, we do NOT need to use feature scaling for clasification.
This is classification as depenednt variable or target is categorical and therefor this is a 
classification problem.

But for regression where dependent variable or y can take a huge range/scale unlike classification), 
we need to use feature scaling for y as well

In [15]:
print(X_train) # All numbers range between -1 to +1 because of feature scaling
print('--------------------------------------------------------------')
print(X_test) # All numbers range between -1 to +1 because of feature scaling
print('--------------------------------------------------------------')
print(y_train) # No feature scaling for classification (classification because categorical dependent variable)
print('--------------------------------------------------------------')
print(y_test) # No feature scaling for classification (classification because categorical dependent variable)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
--------------------------------------------------------------
[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]
--------------------------------------------------------------
[1 1 1 0 1 0 0 1]
--------------------------------------------------------------
[0 0]
