# Machine Learning A-Z Python

## Regression

## Part 2. Multiple Linear Regression (Continuous regression)

### Criteria: Linear regression problems with multiple features

* Simple linear regression (Previous notebook): 1 independent/predictor variable


    
* Multiple linear regression: Multiple independent/predictor variable

Here we are hired as the data scientist for the VC firm who wants to figure out rationale behind more profit. Therefore, dependent variable is profit. We are trying to understand what feature/s ensure higher profit. 

In [168]:
# Data Preprocessing

# Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset=pd.read_csv('50_Startups.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [169]:
X=dataset.iloc[:,:-1] # all independent variables
print(X.head())
print('------------------------------------')
print(X.shape)
X['State'].nunique() # 3 categories

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida
------------------------------------
(50, 4)


3

In [170]:
y=dataset.iloc[:,-1] # dependent | target variable
print(y.head())
print('------------------------------------')
y.shape

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64
------------------------------------


(50,)

**Independent variable: All except Profit | Dependent variable: Profit**

In [171]:
X=dataset.iloc[:,:-1].values # matrix of all independent variables
y=dataset.iloc[:,-1].values # dependent variable vector
print(X[:5]) 
print('------------------------------------')
print(y[:5]) 
print('------------------------------------')
print(X.shape, y.shape)
X.ndim, y.ndim

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']]
------------------------------------
[192261.83 191792.06 191050.39 182901.99 166187.94]
------------------------------------
(50, 4) (50,)


(2, 1)

## Encoding categorical data

### Categorical variables need to be converted into numbers for ML: Salary column has 3 categories

Categorical variables can be converted into numerical values by **LabelEncoder**. But it might lead to weightage biasness.

Then to remove any weightage biasness we will convert that numerical column (made from 
categorical column) into DUMMY variables by **OneHotEncoder**. OneHotEncoder only work on 
numerical column.

In [172]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X=LabelEncoder()
print(X[:5]) # before using labelencoder
print('---------------------------------------')

X[:,-1]=labelencoder_X.fit_transform(X[:,-1])
print(X[:5]) # after using LabelEncoder
print('---------------------------------------')

print(X[:15,3]) # State converting into numerical column

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']]
---------------------------------------
[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 1]]
---------------------------------------
[2 0 1 2 1 2 0 1 2 0 1 0 1 0 1]


Although above code helped to remove state name but it got replaced with 0, 1, 2 and it will lead to weightage biasness. (example-ML will think 1 state is bigger than other as 2>0.) 

To prevent this use **'Dummy variable'**. Make n number of columns based on n number of categories in a column. And each column will have 1 or 0 based on whether it is present or not

In [173]:
import warnings
warnings.filterwarnings('ignore')

In [174]:
onehotencoder= OneHotEncoder(categorical_features=[-1])
X=onehotencoder.fit_transform(X).toarray()

print(X[:2,:]) 
print('---------------------------------------')
X.shape

[[0.0000000e+00 0.0000000e+00 1.0000000e+00 1.6534920e+05 1.3689780e+05
  4.7178410e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.6259770e+05 1.5137759e+05
  4.4389853e+05]]
---------------------------------------


(50, 6)

Previously there were 4 columns in X. After 1 OneHotEncoder last column with 3 categories is converted into 3 columns. so total column will be (4-1)+3=6 columns. Remove 1 of the columns generated by dummy variable, which is redundant (inputs in 2 columns will tell us input in the 3rd column), which will lead to total 5 columns.

In [175]:
# Avoiding Dummy Variable TRAP!
X=X[:,1:] # Remove 1 dummy variable column to prevent dummy variable trap!

X.shape # X(50,6) ---> (50,5) confirming removal

(50, 5)

In [176]:
## Splitting the dataset into the Training and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X, y, 
                                                  test_size=0.2, 
                                                  random_state=0)

In [177]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression # LinearRegression class

regressor = LinearRegression() # Regressor is the object of LinearRegression class

regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [178]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

y_pred

array([103015.20159796, 132582.27760816, 132447.73845175,  71976.09851258,
       178537.48221056, 116161.24230165,  67851.69209676,  98791.73374687,
       113969.43533013, 167921.06569551])

Can't visualize here unlike simple linear regression as we need 5 dimensions because 4 Independent & 1 dependent variable. So we predicted based on the model. But do we need to use all the independent variables for the model building and prediction? Or could we find out the independent variables that have more impact on the dependent variable! 

In [179]:
# Building the optimal model using Backward Elimination

We can use all independent variables to predict the target variable. But there might be some
independent variable that are statistically more significant i.e. they have more impact on dependent
variable or Profit. And some are statistically insignificant and have low/no impact on Profit.

And we will still get great prediction even if we remove the statistically 
insignificant variables.

#### Overall goal: to find an optimal team of independent variable, that has a great impact on dependent variable (Profit) and thus they are great predictors for dependent variable

In [180]:
import statsmodels.formula.api as sm

In multiple linear regression equation, there is `bo` which is a constant, but there is no
`Xo`(independent variable) associated with `bo` unlike seen in the case of all independent variables (eg- `X1` with `b1`, 
`X2` with `b2`). Linear Regression from sklearn considers `bo`, but statsmodel DO NOT consider `bo`. But we still need to use statsmodel as we need to calculate `p-value` and statistical significance of the independent variables.
Therefore, we can add a new column `Xo` where all of its value will be 1 i.e. `Xo=1`.
Because if `Xo=1` then `boXo = bo`. So `Xo=1` will NOT affect `bo` value.

PROBLEM: The statsmodels we are using do NOT consider `bo`. That's a problem!
We see matrix X contains independent features and dummy variables. 
There is no `Xo` for `bo`.

#### In sklearn.linear_model, bo is included but NOT in the case of statsmodels. 
#### Solution: Take X matrix and add a column (contianing value 1 and can act as Xo).

In [181]:
X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)

print(X.shape)
# X(50,5)-->(50,6) confirming addition of Xo column with constant value 1
print('---------------------------------------')
print(X[:2])

(50, 6)
---------------------------------------
[[1.0000000e+00 0.0000000e+00 1.0000000e+00 1.6534920e+05 1.3689780e+05
  4.7178410e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.6259770e+05 1.5137759e+05
  4.4389853e+05]]


**`X = np.append(arr = X,  values = np.ones((50,1)).astype(int),axis = 1)`** - This will add the new array containing 1 at the end of the matrix X.

To add the array at the beginning of the matrix X, `swap arr and values`, i.e.
**`X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)`**

In [182]:
# Backward Elimination

We need to create a new matrix of features called **optimal matrix of features** and we 
will name it **X_opt**. The team of independent variables which will make `X_opt` will be 
statistically significant (have higher impact) for predicting dependent variable (Profit here).


Here we will follow backward elimination. Therefore we include all independent variables 
and then we replace one independent variable at a time if their 
     `p value > SL` (generally Significance Level is 0.05 or 5%), one with the highest p value will be removed. 
That means overall, independent variables that are NOT statistically significant will be removed.

In [183]:
# For backward elimination, X_opt initially contains all independent variables
X_opt = X[:,[0,1,2,3,4,5]] 


X_opt.shape

(50, 6)

In [184]:
# Backward Elimination (Fit full model with all possible predictors)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()

# OLS = Ordinary least square fitted in the X_opt and dependent variable
# OLS is the class. regressor_OLS is the object.

Under OLS documentation, it is mentioned in 'exog' it don't include an intercept and that's why we had 
to append a column with values 1 to make it `Xo` in last step

In [185]:
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Tue, 23 Oct 2018   Prob (F-statistic):           1.34e-27
Time:                        14:50:52   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.0

**Summary function will help us to know p value for each Independent variables. Then we will 
compare it to the significance level (SL) to decide whether it needs to be removed 
or not from the model**

* Consider predictor or Independent variable with highest P value (P).

* If it's `P > Significance Level` --> remove predictor, otherwise Model finished

**RESULT:** Now look into the **P values** `(P > |t|)`, lower the P value more statistically 
significant Independent variable is going to be. 

Constant **(const)** is `Xo`, that we added to the X (array of 1).
Then `X1`, `X2` are dummary variables, `X3` is R&D spend, `X4` is administration spend,
`X5` is marketing spend. Now we have to look for highest p-Value. 

`X2` has highest P value i.e. 99%. That is WAY above Significance Level of 5%, so `X2` has to be removed

In [186]:
# Remove X2 
X_opt = X[:,[0,1,3,4,5]] 

# X_opt now contains Independent variables without predictor X2
X_opt.shape

(50, 5)

In [187]:
# Fit full model with rest predictors again
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Tue, 23 Oct 2018   Prob (F-statistic):           8.49e-29
Time:                        14:50:52   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.0

 **Result:** `X1` has highest P value i.e. 94%. That is WAY above SL of 5%, so X1 has to be removed

In [188]:
# Remove X1 (predictor) and again fit model with non-eliminated predictors
X_opt = X[:,[0,3,4,5]]
print(X_opt.shape)

regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
print(regressor_OLS.summary())

(50, 4)
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Tue, 23 Oct 2018   Prob (F-statistic):           4.53e-30
Time:                        14:50:52   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626 

**RESULT:** `X2`(Admin. expense) has highest P value i.e. 60%. That is above SL of 5%, so `X2` has to be removed

In [189]:
# Remove X2 (predictor) and Again fit model with non-eliminated predictor
X_opt = X[:,[0,3,5]]
print(X_opt.shape)

regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
print(regressor_OLS.summary())

(50, 3)
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Tue, 23 Oct 2018   Prob (F-statistic):           2.16e-31
Time:                        14:50:52   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464 

**RESULT:** `X2` has highest P value i.e. 6%. That is above SL of 5%, so `X2` has to be removed.

**Note:** We can also set SL at 10%, then `X2` would be included. But if we have to follow
Backward elimination framework which has SL of 5%, then `X2` has to be eliminated.

But as 6% is very close to 5%(significance level), we can also confirm Marketing spend should be eliminated or not looking into other factors such as R squared and adjusted R squared. Those will be covered in future notebooks.

In [190]:
# Remove X2 (predictor) and again fit model with non-eliminated predictor
X_opt = X[:,[0,3]]
print(X_opt.shape)

regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit() 
print(regressor_OLS.summary())

(50, 2)
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Tue, 23 Oct 2018   Prob (F-statistic):           3.50e-32
Time:                        14:50:52   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320 

**RESULT:** **None has more than 5%**

**Therefore, X1 i.e. R&D spend is a powerful predictor of profit (dependent variable).**
Therefore, X_opt instead of having a team of independent variables (predictor variables) will only contain 1 independent variable i.e. R&D spend (when just following backward elimination strictly).

In [191]:
## Note 46: Automated Backward Elimination

### Backward Elimination with p-values only:

In [194]:
from statsmodels.formula.api import OLS


def backwardelimination(x_opt,sl):

    model_ols=OLS(y,x_opt).fit()
    p=max(model_ols.pvalues).astype(float)

    if p>sl:
        pos=0
        while model_ols.pvalues[pos].astype(float)!=p:
            pos=pos+1
            x_opt=np.delete(x_opt,pos,1)

        return backwardelimination(x_opt,sl)

    else:
        return x_opt


    
SL = 0.05
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
X_Modeled = backwardElimination(X_opt, SL)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Tue, 23 Oct 2018   Prob (F-statistic):           2.16e-31
Time:                        14:51:12   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.0

### Backward Elimination with p-values and Adjusted R Squared:

In [193]:
import statsmodels.formula.api as sm
def backwardElimination(x, SL):
    numVars = len(x[0])
    temp = np.zeros((50,6)).astype(int)
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        adjR_before = regressor_OLS.rsquared_adj.astype(float)
        if maxVar > SL:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    temp[:,j] = x[:, j]
                    x = np.delete(x, j, 1)
                    tmp_regressor = sm.OLS(y, x).fit()
                    adjR_after = tmp_regressor.rsquared_adj.astype(float)
                    if (adjR_before >= adjR_after):
                        x_rollback = np.hstack((x, temp[:,[0,j]]))
                        x_rollback = np.delete(x_rollback, j, 1)
                        print (regressor_OLS.summary())
                        return x_rollback
                    else:
                        continue
    regressor_OLS.summary()
    return x
 
SL = 0.05
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
X_Modeled = backwardElimination(X_opt, SL)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Tue, 23 Oct 2018   Prob (F-statistic):           2.16e-31
Time:                        14:51:07   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.0